<?php

namespace Systha\Core\Database\Seeders;

use Illuminate\Database\Seeder;
use Systha\Core\Models\ServiceItem;
use Systha\Core\Models\Tenant;
use Systha\Core\Models\TenantMember;
use Systha\Core\Models\Person;
use Systha\Core\Models\Role;
use Systha\Core\Models\TenantServiceItem;

class SvcTenantSeeder extends Seeder
{
    public function run(): void
    {
        $tenantData = [
            [
                'name' => 'RapidFix Services',
                'code' => 'SYS-ABCD23',
                'status' => 'active',
                'timezone' => 'America/New_York',
                'currency' => 'USD',
                'phone' => '+1-555-0101',
                'logo' => 'https://picsum.photos/seed/tenant-01/96/96',
                'address' => [
                    'type' => 'office',
                    'line_1' => '101 Main Street',
                    'city' => 'New York',
                    'state' => 'NY',
                    'zip' => '10001',
                    'country' => 'USA',
                    'lat' => 40.7128,
                    'lng' => -74.0060,
                    'is_primary' => true,
                ],
                'members' => [
                    [
                        'fname' => 'John',
                        'lname' => 'Doe',
                        'email' => 'john.doe@rapidfix.com',
                        'role' => 'owner',
                        'status' => 'active',
                        'is_active' => true,
                        'password' => bcrypt('password'),
                        'address' => [
                            'type' => 'home',
                            'line_1' => '1 Oakwood Ave',
                            'city' => 'Brooklyn',
                            'state' => 'NY',
                            'zip' => '11201',
                            'country' => 'USA',
                            'lat' => 40.6782,
                            'lng' => -73.9442,
                            'is_primary' => true,
                        ],
                    ],
                    [
                        'fname' => 'Jane',
                        'lname' => 'Smith',
                        'email' => 'jane.smith@rapidfix.com',
                        'role' => 'staff',
                        'status' => 'active',
                        'is_active' => true,
                        'password' => bcrypt('password'),
                        'address' => [
                            'type' => 'home',
                            'line_1' => '2 Maple St',
                            'city' => 'Queens',
                            'state' => 'NY',
                            'zip' => '11354',
                            'country' => 'USA',
                            'lat' => 40.7282,
                            'lng' => -73.7949,
                            'is_primary' => true,
                        ],
                    ],
                ],
            ],
            [
                'name' => 'PrimeCare Pros',
                'code' => 'SYS-EFGH24',
                'status' => 'active',
                'timezone' => 'America/New_York',
                'currency' => 'USD',
                'phone' => '+1-555-0102',
                'logo' => 'https://picsum.photos/seed/tenant-02/96/96',
                'address' => [
                    'type' => 'office',
                    'line_1' => '102 Main Street',
                    'city' => 'Los Angeles',
                    'state' => 'CA',
                    'zip' => '90001',
                    'country' => 'USA',
                    'lat' => 34.0522,
                    'lng' => -118.2437,
                    'is_primary' => true,
                ],
                'members' => [
                    [
                        'fname' => 'Alice',
                        'lname' => 'Johnson',
                        'email' => 'alice.johnson@primecare.com',
                        'role' => 'owner',
                        'status' => 'active',
                        'is_active' => true,
                        'password' => bcrypt('password'),
                        'address' => [
                            'type' => 'home',
                            'line_1' => '3 Pine St',
                            'city' => 'San Francisco',
                            'state' => 'CA',
                            'zip' => '94101',
                            'country' => 'USA',
                            'lat' => 37.7749,
                            'lng' => -122.4194,
                            'is_primary' => true,
                        ],
                    ],
                    [
                        'fname' => 'Bob',
                        'lname' => 'Brown',
                        'email' => 'bob.brown@primecare.com',
                        'role' => 'staff',
                        'status' => 'active',
                        'is_active' => true,
                        'password' => bcrypt('password'),
                        'address' => [
                            'type' => 'home',
                            'line_1' => '4 Cedar Rd',
                            'city' => 'San Diego',
                            'state' => 'CA',
                            'zip' => '92101',
                            'country' => 'USA',
                            'lat' => 32.7157,
                            'lng' => -117.1611,
                            'is_primary' => true,
                        ],
                    ],
                ],
            ],
            [
                'name' => 'HomeNest Experts',
                'code' => 'SYS-JKLM25',
                'status' => 'active',
                'timezone' => 'America/New_York',
                'currency' => 'USD',
                'phone' => '+1-555-0103',
                'logo' => 'https://picsum.photos/seed/tenant-03/96/96',
                'address' => [
                    'type' => 'office',
                    'line_1' => '103 Main Street',
                    'city' => 'Chicago',
                    'state' => 'IL',
                    'zip' => '60601',
                    'country' => 'USA',
                    'lat' => 41.8781,
                    'lng' => -87.6298,
                    'is_primary' => true,
                ],
                'members' => [
                    [
                        'fname' => 'Charlie',
                        'lname' => 'Davis',
                        'email' => 'charlie.davis@homenest.com',
                        'role' => 'owner',
                        'status' => 'active',
                        'is_active' => true,
                        'password' => bcrypt('password'),
                        'address' => [
                            'type' => 'home',
                            'line_1' => '5 Elm St',
                            'city' => 'Houston',
                            'state' => 'TX',
                            'zip' => '77001',
                            'country' => 'USA',
                            'lat' => 29.7604,
                            'lng' => -95.3698,
                            'is_primary' => true,
                        ],
                    ],
                    [
                        'fname' => 'Dana',
                        'lname' => 'White',
                        'email' => 'dana.white@homenest.com',
                        'role' => 'staff',
                        'status' => 'active',
                        'is_active' => true,
                        'password' => bcrypt('password'),
                        'address' => [
                            'type' => 'home',
                            'line_1' => '6 Willow Ln',
                            'city' => 'Phoenix',
                            'state' => 'AZ',
                            'zip' => '85001',
                            'country' => 'USA',
                            'lat' => 33.4484,
                            'lng' => -112.0740,
                            'is_primary' => true,
                        ],
                    ],
                ],
            ],
            [
                'name' => 'UrbanShield Solutions',
                'code' => 'SYS-NOPQ26',
                'status' => 'active',
                'timezone' => 'America/New_York',
                'currency' => 'USD',
                'phone' => '+1-555-0104',
                'logo' => 'https://picsum.photos/seed/tenant-04/96/96',
                'address' => [
                    'type' => 'office',
                    'line_1' => '104 Main Street',
                    'city' => 'Philadelphia',
                    'state' => 'PA',
                    'zip' => '19101',
                    'country' => 'USA',
                    'lat' => 39.9526,
                    'lng' => -75.1652,
                    'is_primary' => true,
                ],
                'members' => [
                    [
                        'fname' => 'Eve',
                        'lname' => 'Black',
                        'email' => 'eve.black@urbanshield.com',
                        'role' => 'owner',
                        'status' => 'active',
                        'is_active' => true,
                        'password' => bcrypt('password'),
                        'address' => [
                            'type' => 'home',
                            'line_1' => '7 Sunset Blvd',
                            'city' => 'San Antonio',
                            'state' => 'TX',
                            'zip' => '78201',
                            'country' => 'USA',
                            'lat' => 29.4241,
                            'lng' => -98.4936,
                            'is_primary' => true,
                        ],
                    ],
                    [
                        'fname' => 'Frank',
                        'lname' => 'Green',
                        'email' => 'frank.green@urbanshield.com',
                        'role' => 'staff',
                        'status' => 'active',
                        'is_active' => true,
                        'password' => bcrypt('password'),
                        'address' => [
                            'type' => 'home',
                            'line_1' => '8 River Rd',
                            'city' => 'Dallas',
                            'state' => 'TX',
                            'zip' => '75201',
                            'country' => 'USA',
                            'lat' => 32.7767,
                            'lng' => -96.7970,
                            'is_primary' => true,
                        ],
                    ],
                ],
            ],
            [
                'name' => 'GreenEdge Maintenance',
                'code' => 'SYS-RSTU27',
                'status' => 'active',
                'timezone' => 'America/New_York',
                'currency' => 'USD',
                'phone' => '+1-555-0105',
                'logo' => 'https://picsum.photos/seed/tenant-05/96/96',
                'address' => [
                    'type' => 'office',
                    'line_1' => '105 Main Street',
                    'city' => 'San Diego',
                    'state' => 'CA',
                    'zip' => '92102',
                    'country' => 'USA',
                    'lat' => 32.7157,
                    'lng' => -117.1611,
                    'is_primary' => true,
                ],
                'members' => [
                    [
                        'fname' => 'Grace',
                        'lname' => 'Hopper',
                        'email' => 'grace.hopper@greenedge.com',
                        'role' => 'owner',
                        'status' => 'active',
                        'is_active' => true,
                        'password' => bcrypt('password'),
                        'address' => [
                            'type' => 'home',
                            'line_1' => '9 Hillcrest Dr',
                            'city' => 'Austin',
                            'state' => 'TX',
                            'zip' => '73301',
                            'country' => 'USA',
                            'lat' => 30.2672,
                            'lng' => -97.7431,
                            'is_primary' => true,
                        ],
                    ],
                    [
                        'fname' => 'Heidi',
                        'lname' => 'Watson',
                        'email' => 'heidi.watson@greenedge.com',
                        'role' => 'staff',
                        'status' => 'active',
                        'is_active' => true,
                        'password' => bcrypt('password'),
                        'address' => [
                            'type' => 'home',
                            'line_1' => '10 Lakeview Ave',
                            'city' => 'Seattle',
                            'state' => 'WA',
                            'zip' => '98101',
                            'country' => 'USA',
                            'lat' => 47.6062,
                            'lng' => -122.3321,
                            'is_primary' => true,
                        ],
                    ],
                ],
            ],
            [
                'name' => 'TrueNorth Contractors',
                'code' => 'SYS-VWXY28',
                'status' => 'active',
                'timezone' => 'America/New_York',
                'currency' => 'USD',
                'phone' => '+1-555-0106',
                'logo' => 'https://picsum.photos/seed/tenant-06/96/96',
                'address' => [
                    'type' => 'office',
                    'line_1' => '106 Main Street',
                    'city' => 'San Jose',
                    'state' => 'CA',
                    'zip' => '95101',
                    'country' => 'USA',
                    'lat' => 37.3382,
                    'lng' => -121.8863,
                    'is_primary' => true,
                ],
                'members' => [
                    [
                        'fname' => 'Ivan',
                        'lname' => 'Petrov',
                        'email' => 'ivan.petrov@truenorth.com',
                        'role' => 'owner',
                        'status' => 'active',
                        'is_active' => true,
                        'password' => bcrypt('password'),
                        'address' => [
                            'type' => 'home',
                            'line_1' => '11 Birch St',
                            'city' => 'Denver',
                            'state' => 'CO',
                            'zip' => '80201',
                            'country' => 'USA',
                            'lat' => 39.7392,
                            'lng' => -104.9903,
                            'is_primary' => true,
                        ],
                    ],
                    [
                        'fname' => 'Judy',
                        'lname' => 'Thompson',
                        'email' => 'judy.thompson@truenorth.com',
                        'role' => 'staff',
                        'status' => 'active',
                        'is_active' => true,
                        'password' => bcrypt('password'),
                        'address' => [
                            'type' => 'home',
                            'line_1' => '12 Spruce St',
                            'city' => 'Boston',
                            'state' => 'MA',
                            'zip' => '02101',
                            'country' => 'USA',
                            'lat' => 42.3601,
                            'lng' => -71.0589,
                            'is_primary' => true,
                        ],
                    ],
                ],
            ],
            [
                'name' => 'BlueLine Facilities',
                'code' => 'SYS-ZABC29',
                'status' => 'active',
                'timezone' => 'America/New_York',
                'currency' => 'USD',
                'phone' => '+1-555-0107',
                'logo' => 'https://picsum.photos/seed/tenant-07/96/96',
                'address' => [
                    'type' => 'office',
                    'line_1' => '107 Main Street',
                    'city' => 'Austin',
                    'state' => 'TX',
                    'zip' => '73302',
                    'country' => 'USA',
                    'lat' => 30.2672,
                    'lng' => -97.7431,
                    'is_primary' => true,
                ],
                'members' => [
                    [
                        'fname' => 'Karen',
                        'lname' => 'Williams',
                        'email' => 'karen.williams@blueline.com',
                        'role' => 'owner',
                        'status' => 'active',
                        'is_active' => true,
                        'password' => bcrypt('password'),
                        'address' => [
                            'type' => 'home',
                            'line_1' => '13 Cedar Rd',
                            'city' => 'Seattle',
                            'state' => 'WA',
                            'zip' => '98102',
                            'country' => 'USA',
                            'lat' => 47.6062,
                            'lng' => -122.3321,
                            'is_primary' => true,
                        ],
                    ],
                    [
                        'fname' => 'Laura',
                        'lname' => 'Martinez',
                        'email' => 'laura.martinez@blueline.com',
                        'role' => 'staff',
                        'status' => 'active',
                        'is_active' => true,
                        'password' => bcrypt('password'),
                        'address' => [
                            'type' => 'home',
                            'line_1' => '14 Pine St',
                            'city' => 'Portland',
                            'state' => 'OR',
                            'zip' => '97201',
                            'country' => 'USA',
                            'lat' => 45.5155,
                            'lng' => -122.6793,
                            'is_primary' => true,
                        ],
                    ],
                ],
            ],
            [
                'name' => 'Apex Utility Pros',
                'code' => 'SYS-DEFG30',
                'status' => 'active',
                'timezone' => 'America/New_York',
                'currency' => 'USD',
                'phone' => '+1-555-0108',
                'logo' => 'https://picsum.photos/seed/tenant-08/96/96',
                'address' => [
                    'type' => 'office',
                    'line_1' => '108 Main Street',
                    'city' => 'San Francisco',
                    'state' => 'CA',
                    'zip' => '94102',
                    'country' => 'USA',
                    'lat' => 37.7749,
                    'lng' => -122.4194,
                    'is_primary' => true,
                ],
                'members' => [
                    [
                        'fname' => 'Mike',
                        'lname' => 'Davis',
                        'email' => 'mike.davis@apexutility.com',
                        'role' => 'owner',
                        'status' => 'active',
                        'is_active' => true,
                        'password' => bcrypt('password'),
                        'address' => [
                            'type' => 'home',
                            'line_1' => '15 Oakwood Ave',
                            'city' => 'Los Angeles',
                            'state' => 'CA',
                            'zip' => '90002',
                            'country' => 'USA',
                            'lat' => 34.0522,
                            'lng' => -118.2437,
                            'is_primary' => true,
                        ],
                    ],
                    [
                        'fname' => 'Nina',
                        'lname' => 'Garcia',
                        'email' => 'nina.garcia@apexutility.com',
                        'role' => 'staff',
                        'status' => 'active',
                        'is_active' => true,
                        'password' => bcrypt('password'),
                        'address' => [
                            'type' => 'home',
                            'line_1' => '16 Maple St',
                            'city' => 'San Diego',
                            'state' => 'CA',
                            'zip' => '92102',
                            'country' => 'USA',
                            'lat' => 32.7157,
                            'lng' => -117.1611,
                            'is_primary' => true,
                        ],
                    ],
                ],
            ],
            [
                'name' => 'SilverOak Service Co',
                'code' => 'SYS-HJKL32',
                'status' => 'active',
                'timezone' => 'America/New_York',
                'currency' => 'USD',
                'phone' => '+1-555-0109',
                'logo' => 'https://picsum.photos/seed/tenant-09/96/96',
                'address' => [
                    'type' => 'office',
                    'line_1' => '109 Main Street',
                    'city' => 'Seattle',
                    'state' => 'WA',
                    'zip' => '98102',
                    'country' => 'USA',
                    'lat' => 47.6062,
                    'lng' => -122.3321,
                    'is_primary' => true,
                ],
                'members' => [
                    [
                        'fname' => 'Oscar',
                        'lname' => 'Lee',
                        'email' => 'oscar.lee@silveroak.com',
                        'role' => 'owner',
                        'status' => 'active',
                        'is_active' => true,
                        'password' => bcrypt('password'),
                        'address' => [
                            'type' => 'home',
                            'line_1' => '17 Birch St',
                            'city' => 'Portland',
                            'state' => 'OR',
                            'zip' => '97202',
                            'country' => 'USA',
                            'lat' => 45.5155,
                            'lng' => -122.6793,
                            'is_primary' => true,
                        ],
                    ],
                    [
                        'fname' => 'Paul',
                        'lname' => 'Walker',
                        'email' => 'paul.walker@silveroak.com',
                        'role' => 'staff',
                        'status' => 'active',
                        'is_active' => true,
                        'password' => bcrypt('password'),
                        'address' => [
                            'type' => 'home',
                            'line_1' => '18 Cedar Rd',
                            'city' => 'San Jose',
                            'state' => 'CA',
                            'zip' => '95102',
                            'country' => 'USA',
                            'lat' => 37.3382,
                            'lng' => -121.8863,
                            'is_primary' => true,
                        ],
                    ],
                ],
            ],
            [
                'name' => 'MetroGuard Support',
                'code' => 'SYS-MNOP34',
                'status' => 'active',
                'timezone' => 'America/New_York',
                'currency' => 'USD',
                'phone' => '+1-555-0110',
                'logo' => 'https://picsum.photos/seed/tenant-10/96/96',
                'address' => [
                    'type' => 'office',
                    'line_1' => '110 Main Street',
                    'city' => 'Austin',
                    'state' => 'TX',
                    'zip' => '73303',
                    'country' => 'USA',
                    'lat' => 30.2672,
                    'lng' => -97.7431,
                    'is_primary' => true,
                ],
                'members' => [
                    [
                        'fname' => 'Nancy',
                        'lname' => 'Drew',
                        'email' => 'nancy.drew@metroguard.com',
                        'role' => 'owner',
                        'status' => 'active',
                        'is_active' => true,
                        'password' => bcrypt('password'),
                        'address' => [
                            'type' => 'home',
                            'line_1' => '19 Oakwood Ave',
                            'city' => 'Dallas',
                            'state' => 'TX',
                            'zip' => '75202',
                            'country' => 'USA',
                            'lat' => 32.7767,
                            'lng' => -96.7970,
                            'is_primary' => true,
                        ],
                    ],
                    [
                        'fname' => 'Oliver',
                        'lname' => 'Twist',
                        'email' => 'oliver.twist@metroguard.com',
                        'role' => 'staff',
                        'status' => 'active',
                        'is_active' => true,
                        'password' => bcrypt('password'),
                        'address' => [
                            'type' => 'home',
                            'line_1' => '20 Maple St',
                            'city' => 'San Antonio',
                            'state' => 'TX',
                            'zip' => '78202',
                            'country' => 'USA',
                            'lat' => 29.4241,
                            'lng' => -98.4936,
                            'is_primary' => true,
                        ],
                    ],
                ],
            ],
            [
                'name' => 'EverClean Team',
                'code' => 'SYS-QRST35',
                'status' => 'active',
                'timezone' => 'America/New_York',
                'currency' => 'USD',
                'phone' => '+1-555-0111',
                'logo' => 'https://picsum.photos/seed/tenant-11/96/96',
                'address' => [
                    'type' => 'office',
                    'line_1' => '111 Main Street',
                    'city' => 'Houston',
                    'state' => 'TX',
                    'zip' => '77002',
                    'country' => 'USA',
                    'lat' => 29.7604,
                    'lng' => -95.3698,
                    'is_primary' => true,
                ],
                'members' => [
                    [
                        'fname' => 'Quincy',
                        'lname' => 'Adams',
                        'email' => 'quincy.adams@everclean.com',
                        'role' => 'owner',
                        'status' => 'active',
                        'is_active' => true,
                        'password' => bcrypt('password'),
                        'address' => [
                            'type' => 'home',
                            'line_1' => '21 Birch St',
                            'city' => 'Phoenix',
                            'state' => 'AZ',
                            'zip' => '85002',
                            'country' => 'USA',
                            'lat' => 33.4484,
                            'lng' => -112.0740,
                            'is_primary' => true,
                        ],
                    ],
                    [
                        'fname' => 'Rachel',
                        'lname' => 'Green',
                        'email' => 'rachel.green@everclean.com',
                        'role' => 'staff',
                        'status' => 'active',
                        'is_active' => true,
                        'password' => bcrypt('password'),
                        'address' => [
                            'type' => 'home',
                            'line_1' => '22 Cedar Rd',
                            'city' => 'San Diego',
                            'state' => 'CA',
                            'zip' => '92103',
                            'country' => 'USA',
                            'lat' => 32.7157,
                            'lng' => -117.1611,
                            'is_primary' => true,
                        ],
                    ],
                ],
            ],
            [
                'name' => 'GoldLeaf Home Services',
                'code' => 'SYS-UVWX36',
                'status' => 'active',
                'timezone' => 'America/New_York',
                'currency' => 'USD',
                'phone' => '+1-555-0112',
                'logo' => 'https://picsum.photos/seed/tenant-12/96/96',
                'address' => [
                    'type' => 'office',
                    'line_1' => '112 Main Street',
                    'city' => 'Dallas',
                    'state' => 'TX',
                    'zip' => '75203',
                    'country' => 'USA',
                    'lat' => 32.7767,
                    'lng' => -96.7970,
                    'is_primary' => true,
                ],
                'members' => [
                    [
                        'fname' => 'Sam',
                        'lname' => 'Wilson',
                        'email' => 'sam.wilson@goldleaf.com',
                        'role' => 'owner',
                        'status' => 'active',
                        'is_active' => true,
                        'password' => bcrypt('password'),
                        'address' => [
                            'type' => 'home',
                            'line_1' => '23 Oakwood Ave',
                            'city' => 'San Antonio',
                            'state' => 'TX',
                            'zip' => '78203',
                            'country' => 'USA',
                            'lat' => 29.4241,
                            'lng' => -98.4936,
                            'is_primary' => true,
                        ],
                    ],
                    [
                        'fname' => 'Tina',
                        'lname' => 'Turner',
                        'email' => 'tina.turner@goldleaf.com',
                        'role' => 'staff',
                        'status' => 'active',
                        'is_active' => true,
                        'password' => bcrypt('password'),
                        'address' => [
                            'type' => 'home',
                            'line_1' => '24 Maple St',
                            'city' => 'Austin',
                            'state' => 'TX',
                            'zip' => '73303',
                            'country' => 'USA',
                            'lat' => 30.2672,
                            'lng' => -97.7431,
                            'is_primary' => true,
                        ],
                    ],
                ],
            ],
            [
                'name' => 'BrightSide Repairs',
                'code' => 'SYS-YZAB37',
                'status' => 'active',
                'timezone' => 'America/New_York',
                'currency' => 'USD',
                'phone' => '+1-555-0113',
                'logo' => 'https://picsum.photos/seed/tenant-13/96/96',
                'address' => [
                    'type' => 'office',
                    'line_1' => '113 Main Street',
                    'city' => 'San Antonio',
                    'state' => 'TX',
                    'zip' => '78204',
                    'country' => 'USA',
                    'lat' => 29.4241,
                    'lng' => -98.4936,
                    'is_primary' => true,
                ],
                'members' => [
                    [
                        'fname' => 'Uma',
                        'lname' => 'Thurman',
                        'email' => 'uma.thurman@brightside.com',
                        'role' => 'owner',
                        'status' => 'active',
                        'is_active' => true,
                        'password' => bcrypt('password'),
                        'address' => [
                            'type' => 'home',
                            'line_1' => '25 Birch St',
                            'city' => 'Houston',
                            'state' => 'TX',
                            'zip' => '77004',
                            'country' => 'USA',
                            'lat' => 29.7604,
                            'lng' => -95.3698,
                            'is_primary' => true,
                        ],
                    ],
                    [
                        'fname' => 'Vince',
                        'lname' => 'Carter',
                        'email' => 'vince.carter@brightside.com',
                        'role' => 'staff',
                        'status' => 'active',
                        'is_active' => true,
                        'password' => bcrypt('password'),
                        'address' => [
                            'type' => 'home',
                            'line_1' => '26 Cedar Rd',
                            'city' => 'Phoenix',
                            'state' => 'AZ',
                            'zip' => '85003',
                            'country' => 'USA',
                            'lat' => 33.4484,
                            'lng' => -112.0740,
                            'is_primary' => true,
                        ],
                    ],
                ],
            ],
            [
                'name' => 'ProTask Crew',
                'code' => 'SYS-CDEF38',
                'status' => 'active',
                'timezone' => 'America/New_York',
                'currency' => 'USD',
                'phone' => '+1-555-0114',
                'logo' => 'https://picsum.photos/seed/tenant-14/96/96',
                'address' => [
                    'type' => 'office',
                    'line_1' => '114 Main Street',
                    'city' => 'Dallas',
                    'state' => 'TX',
                    'zip' => '75204',
                    'country' => 'USA',
                    'lat' => 32.7767,
                    'lng' => -96.7970,
                    'is_primary' => true,
                ],
                'members' => [
                    [
                        'fname' => 'Will',
                        'lname' => 'Smith',
                        'email' => 'will.smith@protask.com',
                        'role' => 'owner',
                        'status' => 'active',
                        'is_active' => true,
                        'password' => bcrypt('password'),
                        'address' => [
                            'type' => 'home',
                            'line_1' => '27 Oakwood Ave',
                            'city' => 'San Diego',
                            'state' => 'CA',
                            'zip' => '92104',
                            'country' => 'USA',
                            'lat' => 32.7157,
                            'lng' => -117.1611,
                            'is_primary' => true,
                        ],
                    ],
                    [
                        'fname' => 'Xena',
                        'lname' => 'Jones',
                        'email' => 'xena.jones@protask.com',
                        'role' => 'staff',
                        'status' => 'active',
                        'is_active' => true,
                        'password' => bcrypt('password'),
                        'address' => [
                            'type' => 'home',
                            'line_1' => '28 Maple St',
                            'city' => 'Los Angeles',
                            'state' => 'CA',
                            'zip' => '90003',
                            'country' => 'USA',
                            'lat' => 34.0522,
                            'lng' => -118.2437,
                            'is_primary' => true,
                        ],
                    ],
                ],
            ],
            [
                'name' => 'NovaCare Specialists',
                'code' => 'SYS-GHJK39',
                'status' => 'active',
                'timezone' => 'America/New_York',
                'currency' => 'USD',
                'phone' => '+1-555-0115',
                'logo' => 'https://picsum.photos/seed/tenant-15/96/96',
                'address' => [
                    'type' => 'office',
                    'line_1' => '115 Main Street',
                    'city' => 'San Francisco',
                    'state' => 'CA',
                    'zip' => '94103',
                    'country' => 'USA',
                    'lat' => 37.7749,
                    'lng' => -122.4194,
                    'is_primary' => true,
                ],
                'members' => [
                    [
                        'fname' => 'Yara',
                        'lname' => 'Khan',
                        'email' => 'yara.khan@novacare.com',
                        'role' => 'owner',
                        'status' => 'active',
                        'is_active' => true,
                        'password' => bcrypt('password'),
                        'address' => [
                            'type' => 'home',
                            'line_1' => '29 Birch St',
                            'city' => 'Seattle',
                            'state' => 'WA',
                            'zip' => '98103',
                            'country' => 'USA',
                            'lat' => 47.6062,
                            'lng' => -122.3321,
                            'is_primary' => true,
                        ],
                    ],
                    [
                        'fname' => 'Zara',
                        'lname' => 'Ali',
                        'email' => 'zara.ali@novacare.com',
                        'role' => 'staff',
                        'status' => 'active',
                        'is_active' => true,
                        'password' => bcrypt('password'),
                        'address' => [
                            'type' => 'home',
                            'line_1' => '30 Cedar Rd',
                            'city' => 'Portland',
                            'state' => 'OR',
                            'zip' => '97203',
                            'country' => 'USA',
                            'lat' => 45.5155,
                            'lng' => -122.6793,
                            'is_primary' => true,
                        ],
                    ],
                ],
            ],
            [
                'name' => 'IronGate Technicians',
                'code' => 'SYS-LMNP40',
                'status' => 'active',
                'timezone' => 'America/New_York',
                'currency' => 'USD',
                'phone' => '+1-555-0116',
                'logo' => 'https://picsum.photos/seed/tenant-16/96/96',
                'address' => [
                    'type' => 'office',
                    'line_1' => '116 Main Street',
                    'city' => 'Los Angeles',
                    'state' => 'CA',
                    'zip' => '90004',
                    'country' => 'USA',
                    'lat' => 34.0522,
                    'lng' => -118.2437,
                    'is_primary' => true,
                ],
                'members' => [
                    [
                        'fname' => 'Bruce',
                        'lname' => 'Wayne',
                        'email' => 'bruce.wayne@irongate.com',
                        'role' => 'owner',
                        'status' => 'active',
                        'is_active' => true,
                        'password' => bcrypt('password'),
                        'address' => [
                            'type' => 'home',
                            'line_1' => '31 Oakwood Ave',
                            'city' => 'San Diego',
                            'state' => 'CA',
                            'zip' => '92105',
                            'country' => 'USA',
                            'lat' => 32.7157,
                            'lng' => -117.1611,
                            'is_primary' => true,
                        ],
                    ],
                    [
                        'fname' => 'Clark',
                        'lname' => 'Kent',
                        'email' => 'clark.kent@irongate.com',
                        'role' => 'staff',
                        'status' => 'active',
                        'is_active' => true,
                        'password' => bcrypt('password'),
                        'address' => [
                            'type' => 'home',
                            'line_1' => '32 Maple St',
                            'city' => 'San Francisco',
                            'state' => 'CA',
                            'zip' => '94104',
                            'country' => 'USA',
                            'lat' => 37.7749,
                            'lng' => -122.4194,
                            'is_primary' => true,
                        ],
                    ],
                ],
            ],
            [
                'name' => 'SwiftHands Network',
                'code' => 'SYS-QRST42',
                'status' => 'active',
                'timezone' => 'America/New_York',
                'currency' => 'USD',
                'phone' => '+1-555-0117',
                'logo' => 'https://picsum.photos/seed/tenant-17/96/96',
                'address' => [
                    'type' => 'office',
                    'line_1' => '117 Main Street',
                    'city' => 'Houston',
                    'state' => 'TX',
                    'zip' => '77003',
                    'country' => 'USA',
                    'lat' => 29.7604,
                    'lng' => -95.3698,
                    'is_primary' => true,
                ],
                'members' => [
                    [
                        'fname' => 'Peter',
                        'lname' => 'Parker',
                        'email' => 'peter.parker@swifthands.com',
                        'role' => 'owner',
                        'status' => 'active',
                        'is_active' => true,
                        'password' => bcrypt('password'),
                        'address' => [
                            'type' => 'home',
                            'line_1' => '33 Birch St',
                            'city' => 'Phoenix',
                            'state' => 'AZ',
                            'zip' => '85004',
                            'country' => 'USA',
                            'lat' => 33.4484,
                            'lng' => -112.0740,
                            'is_primary' => true,
                        ],
                    ],
                    [
                        'fname' => 'Wanda',
                        'lname' => 'Maximoff',
                        'email' => 'wanda.maximoff@swifthands.com',
                        'role' => 'staff',
                        'status' => 'active',
                        'is_active' => true,
                        'password' => bcrypt('password'),
                        'address' => [
                            'type' => 'home',
                            'line_1' => '34 Cedar Rd',
                            'city' => 'San Antonio',
                            'state' => 'TX',
                            'zip' => '78204',
                            'country' => 'USA',
                            'lat' => 29.4241,
                            'lng' => -98.4936,
                            'is_primary' => true,
                        ],
                    ],
                ],
            ],
            [
                'name' => 'ClearPath Service Hub',
                'code' => 'SYS-UVWX43',
                'status' => 'active',
                'timezone' => 'America/New_York',
                'currency' => 'USD',
                'phone' => '+1-555-0118',
                'logo' => 'https://picsum.photos/seed/tenant-18/96/96',
                'address' => [
                    'type' => 'office',
                    'line_1' => '118 Main Street',
                    'city' => 'Dallas',
                    'state' => 'TX',
                    'zip' => '75205',
                    'country' => 'USA',
                    'lat' => 32.7767,
                    'lng' => -96.7970,
                    'is_primary' => true,
                ],
                'members' => [
                    [
                        'fname' => 'Stephen',
                        'lname' => 'Strange',
                        'email' => 'stephen.strange@clearpath.com',
                        'role' => 'owner',
                        'status' => 'active',
                        'is_active' => true,
                        'password' => bcrypt('password'),
                        'address' => [
                            'type' => 'home',
                            'line_1' => '35 Oakwood Ave',
                            'city' => 'San Diego',
                            'state' => 'CA',
                            'zip' => '92105',
                            'country' => 'USA',
                            'lat' => 32.7157,
                            'lng' => -117.1611,
                            'is_primary' => true,
                        ],
                    ],
                    [
                        'fname' => 'Natasha',
                        'lname' => 'Romanoff',
                        'email' => 'natasha.romanoff@clearpath.com',
                        'role' => 'staff',
                        'status' => 'active',
                        'is_active' => true,
                        'password' => bcrypt('password'),
                        'address' => [
                            'type' => 'home',
                            'line_1' => '36 Maple St',
                            'city' => 'Los Angeles',
                            'state' => 'CA',
                            'zip' => '90005',
                            'country' => 'USA',
                            'lat' => 34.0522,
                            'lng' => -118.2437,
                            'is_primary' => true,
                        ],
                    ],
                ],
            ],
            [
                'name' => 'SummitAid Professionals',
                'code' => 'SYS-YZAB44',
                'status' => 'active',
                'timezone' => 'America/New_York',
                'currency' => 'USD',
                'phone' => '+1-555-0119',
                'logo' => 'https://picsum.photos/seed/tenant-19/96/96',
                'address' => [
                    'type' => 'office',
                    'line_1' => '119 Main Street',
                    'city' => 'San Antonio',
                    'state' => 'TX',
                    'zip' => '78205',
                    'country' => 'USA',
                    'lat' => 29.4241,
                    'lng' => -98.4936,
                    'is_primary' => true,
                ],
                'members' => [
                    [
                        'fname' => 'Matt',
                        'lname' => 'Murdock',
                        'email' => 'matt.murdock@summitaid.com',
                        'role' => 'owner',
                        'status' => 'active',
                        'is_active' => true,
                        'password' => bcrypt('password'),
                        'address' => [
                            'type' => 'home',
                            'line_1' => '37 Birch St',
                            'city' => 'Houston',
                            'state' => 'TX',
                            'zip' => '77005',
                            'country' => 'USA',
                            'lat' => 29.7604,
                            'lng' => -95.3698,
                            'is_primary' => true,
                        ],
                    ],
                    [
                        'fname' => 'Jessica',
                        'lname' => 'Jones',
                        'email' => 'jessica.jones@summitaid.com',
                        'role' => 'staff',
                        'status' => 'active',
                        'is_active' => true,
                        'password' => bcrypt('password'),
                        'address' => [
                            'type' => 'home',
                            'line_1' => '38 Cedar Rd',
                            'city' => 'Phoenix',
                            'state' => 'AZ',
                            'zip' => '85005',
                            'country' => 'USA',
                            'lat' => 33.4484,
                            'lng' => -112.0740,
                            'is_primary' => true,
                        ],
                    ],
                ],
            ],
            [
                'name' => 'CoreTrust Field Team',
                'code' => 'SYS-CDEF45',
                'status' => 'active',
                'timezone' => 'America/New_York',
                'currency' => 'USD',
                'phone' => '+1-555-0120',
                'logo' => 'https://picsum.photos/seed/tenant-20/96/96',
                'address' => [
                    'type' => 'office',
                    'line_1' => '120 Main Street',
                    'city' => 'Austin',
                    'state' => 'TX',
                    'zip' => '73304',
                    'country' => 'USA',
                    'lat' => 30.2672,
                    'lng' => -97.7431,
                    'is_primary' => true,
                ],
                'members' => [
                    [
                        'fname' => 'Nick',
                        'lname' => 'Fury',
                        'email' => 'nick.fury@coretrust.com',
                        'role' => 'owner',
                        'status' => 'active',
                        'is_active' => true,
                        'password' => bcrypt('password'),
                        'address' => [
                            'type' => 'home',
                            'line_1' => '39 Oakwood Ave',
                            'city' => 'San Diego',
                            'state' => 'CA',
                            'zip' => '92106',
                            'country' => 'USA',
                            'lat' => 32.7157,
                            'lng' => -117.1611,
                            'is_primary' => true,
                        ],
                    ],
                    [
                        'fname' => 'Clint',
                        'lname' => 'Barton',
                        'email' => 'clint.barton@coretrust.com',
                        'role' => 'staff',
                        'status' => 'active',
                        'is_active' => true,
                        'password' => bcrypt('password'),
                        'address' => [
                            'type' => 'home',
                            'line_1' => '40 Maple St',
                            'city' => 'Los Angeles',
                            'state' => 'CA',
                            'zip' => '90006',
                            'country' => 'USA',
                            'lat' => 34.0522,
                            'lng' => -118.2437,
                            'is_primary' => true,
                        ],
                    ],
                ],
            ],
        ];

        $createdTenants = [];
        $chunkSize = 5; // Adjust chunk size as needed
        foreach (collect($tenantData)->chunk($chunkSize) as $tenantChunk) {
            foreach ($tenantChunk as $tenantInfo) {
                $tenant = Tenant::query()->firstOrNew(['code' => $tenantInfo['code']]);
                $tenant->fill([
                    'name' => $tenantInfo['name'],
                    'code' => $tenantInfo['code'],
                    'status' => $tenantInfo['status'],
                    'timezone' => $tenantInfo['timezone'],
                    'currency' => $tenantInfo['currency'],
                    'phone' => $tenantInfo['phone'],
                    'logo' => $tenantInfo['logo'],
                ]);
                $tenant->save();
                $createdTenants[] = $tenant;

                $tenant->addresses()->updateOrCreate(
                    ['type' => $tenantInfo['address']['type']],
                    $tenantInfo['address']
                );

                foreach ($tenantInfo['members'] as $memberInfo) {
                    $role = Role::query()->firstOrCreate(
                        ['name' => $memberInfo['role']],
                        ['label' => ucfirst($memberInfo['role'])]
                    );

                    $person = Person::query()->firstOrCreate(
                        [
                            'email' => $memberInfo['email'],
                        ],
                        [
                            'first_name' => $memberInfo['fname'],
                            'last_name' => $memberInfo['lname'],
                        ]
                    );

                    $member = TenantMember::query()->firstOrCreate(
                        [
                            'tenant_id' => $tenant->id,
                            'email' => $memberInfo['email'],
                        ],
                        [
                            'person_id' => $person->id,
                            'first_name' => $memberInfo['fname'],
                            'last_name' => $memberInfo['lname'],
                            'username' => $this->buildUniqueMemberUsername($tenant->id, $memberInfo['fname']),
                            'role_id' => $role->id,
                            'status' => $memberInfo['status'],
                            'is_active' => $memberInfo['is_active'],
                            'password' => $memberInfo['password'],
                        ]
                    );
                    $member->addresses()->updateOrCreate(
                        ['type' => $memberInfo['address']['type']],
                        $memberInfo['address']
                    );
                }
            }
        }

        $serviceItemsByGroup = ServiceItem::query()
            ->orderBy('service_group_id')
            ->orderBy('id')
            ->get()
            ->groupBy('service_group_id')
            ->map(function ($items) {
                return $items->take(2);
            });

        foreach ($serviceItemsByGroup as $items) {
            foreach ($items as $index => $serviceItem) {
                foreach ($createdTenants as $tenantIndex => $tenant) {
                    TenantServiceItem::query()->updateOrCreate(
                        [
                            'tenant_id' => $tenant->id,
                            'service_item_id' => $serviceItem->id,
                        ],
                        [
                            'is_active' => true,
                            'base_price' => 100 + ($index * 10),
                            'currency' => 'USD',
                            'lead_time_hours' => 24 + ($tenantIndex * 12),
                        ],
                    );
                }
            }
        }
    }

    private function generateUniqueCode(): string
    {
        $characters = 'ABCDEFGHJKLMNPQRSTUVWXYZ023456789';

        do {
            $random = collect(range(1, 6))
                ->map(fn () => $characters[random_int(0, strlen($characters) - 1)])
                ->implode('');
            $code = 'SYS-' . $random;
        } while (Tenant::query()->where('code', $code)->exists());

        return $code;
    }

    private function buildUniqueMemberUsername(int $tenantId, string $firstName): string
    {
        $base = $this->normalizeUsernamePart($firstName);
        $candidate = 'm_' . $base;
        $suffix = 1;

        while (
            TenantMember::query()
                ->where('tenant_id', $tenantId)
                ->where('username', $candidate)
                ->exists()
        ) {
            $suffix++;
            $candidate = 'm_' . $base . '_' . $suffix;
        }

        return $candidate;
    }

    private function normalizeUsernamePart(string $value): string
    {
        $normalized = strtolower(preg_replace('/[^a-z0-9]/i', '', $value) ?? '');

        return $normalized !== '' ? $normalized : 'member';
    }
}
